from setuptools import setup, find_packages


setup(name="tap-sparkpost",
      version="0.0.1",
      description="Singer.io tap for extracting data from sparkpost API",
      author="Generated by Connector Intelligence",
      url="http://singer.io",
      classifiers=["Programming Language :: Python :: 3 :: Only"],
      install_requires=[
        "singer-python==6.1.1",
        "requests==2.32.4",
        "backoff==2.2.1",
        "parameterized==0.9.0"
      ],
      extras_require={
          "dev": [
              "pytest",
              "coverage",
              "pylint",
          ],
      },
      entry_points="""
          [console_scripts]
          tap-sparkpost=tap_sparkpost:main
      """,
      packages=find_packages(),
      package_data = {
          "tap_sparkpost": ["schemas/*.json", "schemas/shared/*.json"],
      },
      include_package_data=True,
)
